# Version 2 is required for AWS
#version: '2'
version: '3'

services:
  app:
    container_name: hitch_a_ride_app
    environment:
      - DATABASE_URL=postgresql://hitch:admin@postgres:5432/hitch_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379

    build:
     context: ./services/backend
     dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - celery
      - redis
      - client


  postgres:
    image: 'postgres:alpine'
    container_name: hitch_a_ride_db
    environment:
      - POSTGRES_USER=hitch
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hitch_db
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

#volumes:
#  # persist db data
#  postgres-data:


  celery:
    environment:
      - REDIS_URL=redis://redis:6379/0
    user: nobody
    build:
      context: ./services/backend
      dockerfile: Dockerfile-celery

    env_file:
      - ./services/backend/.env

    depends_on:
      - redis


  redis:
    image: 'redis:alpine'

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_URL=http://localhost:5000

#  nginx:
#    build:
#      context: ./services/nginx
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#    - 80:80
#    depends_on:
#      - app